
language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip

before_install:
  - sudo apt-get -qq update
  - mkdir -p ${GOPATH}/bin
  - cd ~
  - curl https://glide.sh/get | sh

install:
  - cd $GOPATH/src/github.com/${TRAVIS_REPO_SLUG}
  - glide install

script:
  - go test
